version: "3.9"
services:
  mysql8:
    image: mysql:8
    security_opt:
      - apparmor:unconfined
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: CROSSTUBE
      MYSQL_USER: batoi
      MYSQL_PASSWORD: 1234
  crostube_app:
    depends_on:
      - mysql8
    build: .
    image: crosstube:v1.0
    ports:
      - "80:80"
    restart: always
volumes:
  db_data: